Fix payload tests return codes

diff --git a/test/network_tests/payload_tests/conf/external_local_payload_test_client_local_starter.sh.in b/test/network_tests/payload_tests/conf/external_local_payload_test_client_local_starter.sh.in
--- a/test/network_tests/payload_tests/conf/external_local_payload_test_client_local_starter.sh.in
+++ b/test/network_tests/payload_tests/conf/external_local_payload_test_client_local_starter.sh.in
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright (C) 2015-2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
+# Copyright (C) 2015-2025 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
@@ -10,6 +10,7 @@
 # the testcase simply executes this script. This script then runs client
 # and service and checks that both exit sucessfully.
 
+# Initialize error tracking
 FAIL=0
 
 # Parameter 1: the pid to check
@@ -52,11 +53,13 @@ check_tcp_udp_sockets_are_closed ()
 export VSOMEIP_APPLICATION_NAME=external_local_payload_test_service
 export VSOMEIP_CONFIGURATION=external_local_payload_test_service.json
 ./payload_test_service &
-SERIVCE_PID=$!
-sleep 2;
+SERVICE_PID=$!
+
+# To ensure that sockets are open
+sleep 2
 
 # The service should listen on a TCP and UDP socket now
-check_tcp_udp_sockets_are_open $SERIVCE_PID 2
+check_tcp_udp_sockets_are_open $SERVICE_PID 2
 
 # Start the client
 export VSOMEIP_APPLICATION_NAME=external_local_payload_test_client_local
@@ -65,7 +68,7 @@ export VSOMEIP_CONFIGURATION=external_local_payload_test_client_local.json
 CLIENT_PID=$!
 
 # The service should still listen on a TCP and UDP socket now
-check_tcp_udp_sockets_are_open  $SERIVCE_PID 2
+check_tcp_udp_sockets_are_open  $SERVICE_PID 2
 # The client should use the shortcut over a local UDS instead of TCP/UDP,
 # therefore he shouldn't have any open TCP/UDP sockets
 check_tcp_udp_sockets_are_closed  $CLIENT_PID
@@ -74,13 +77,10 @@ if [ ! -z "$USE_DOCKER" ]; then
     FAIL=0
 fi
 
-# Wait until client and service are finished
-for job in $(pgrep -P $$)
-do
-   # Fail gets incremented if either client or service exit
-   # with a non-zero exit code
-   wait $job || FAIL=$(($FAIL+1))
-done
+# Fail gets incremented if either client or service exit
+# with a non-zero exit code
+wait $SERVICE_PID || ((FAIL+=1))
+wait $EXTERNAL_CLIENT_PID || ((FAIL+=1))
 
 # Check if client and server both exited sucessfully and the service didnt't
 # have any open tcp/udp sockets
