Adds perf+flamegraph to docker + test update
Adds perf+flamegraph to docker + memory_test updates.
The roles in memory_test are swapped (meaning, slave is the now the client and the
master considers the server). Please find the details/rational here.
Add FlameGraph scripts and optional perf support to the test container
To avoid conflicts the perf will only be executed when VALGRIND_TYPE is not defined or empty.
Note: Profiling is optional and not part of the default workflow. While memory_test demonstrates
the setup, any test binary can be executed with perf in the same way.
Please note that the intent of this PR is not to resolve the memory_tests failures, but rather to make
profiling more accessible.
Perf data together with svg file can be found in: build/test/network_tests/memory_test
The memory_tests are purposely disabled. This is temporary and it will be enabled back
as part of in a separate PR.

diff --git a/test/network_tests/memory_tests/conf/memory_test_master_starter.sh.in b/test/network_tests/memory_tests/conf/memory_test_master_starter.sh.in
--- a/test/network_tests/memory_tests/conf/memory_test_master_starter.sh.in
+++ b/test/network_tests/memory_tests/conf/memory_test_master_starter.sh.in
@@ -9,18 +9,59 @@ if ! source $SCRIPT_DIRECTORY/../setup_test.sh; then
     exit 1
 fi
 
+FLAMEGRAPH_DIR=/opt/flamegraph/
+VALGRIND_TYPE=@VALGRIND_TYPE@
+PERF_TOOL=$(find /usr/lib/linux-tools* -type f -name "perf" | head -n 1)
+
+if [ ! -f "$PERF_TOOL" ]; then
+    echo "Failed to find installation of perf."; exit 1;
+fi
+
 FAIL=0
 
-export VSOMEIP_CONFIGURATION=memory_test_client.json
-export VSOMEIP_APPLICATION_NAME="client-sample"
-./memory_test_client &
+export VSOMEIP_CONFIGURATION=memory_test_service.json
+export VSOMEIP_APPLICATION_NAME="service-sample"
+
+# If VALGRIND_TYPE is empty, run under perf; otherwise run normally
+if [ -z "${VALGRIND_TYPE}" ]; then
+    echo "[flamegraph] Starting memory_test_service under perf recording..."
+    $PERF_TOOL record -F 99 -g -o memory_test_service.perf.data -- ./memory_test_service &
+else
+    ./memory_test_service &
+fi
 PID_MASTER=$!
+echo "[flamegraph] memory_test_service started with PID=$PID_MASTER"
 
 exec_slave "./memory_test_slave_starter.sh"
 PID_SLAVE=$!
 
 wait $PID_MASTER || FAIL=$(($FAIL+1))
 wait $PID_SLAVE || FAIL=$(($FAIL+1))
+
+# Generate flamegraph from recorded perf data (only if VALGRIND_TYPE is empty)
+if [ -z "${VALGRIND_TYPE}" ] && [ -f memory_test_service.perf.data ]; then
+    echo "[flamegraph] Perf data found, generating flamegraph..."
+    # Generate interactive SVG flamegraph (open directly in any browser)
+    $PERF_TOOL script -i memory_test_service.perf.data \
+        | $FLAMEGRAPH_DIR/stackcollapse-perf.pl \
+        | $FLAMEGRAPH_DIR/flamegraph.pl > memory_test_service_flamegraph.svg
+    if [ $? -eq 0 ]; then
+        echo "[flamegraph] SVG flamegraph generated: memory_test_service_flamegraph.svg"
+    else
+        echo "[flamegraph] ERROR: SVG flamegraph generation failed!" >&2
+    fi
+
+    # Generate perf script text file for import into Firefox Profiler
+    # (profiler.firefox.com -> "Load a profile from file")
+    $PERF_TOOL script -i memory_test_service.perf.data > memory_test_service_firefox_profiler.perf
+    if [ $? -eq 0 ]; then
+        echo "[flamegraph] Firefox Profiler file generated: memory_test_service_firefox_profiler.perf"
+    else
+        echo "[flamegraph] ERROR: Firefox Profiler file generation failed!" >&2
+    fi
+elif [ -n "${VALGRIND_TYPE}" ]; then
+    echo "[flamegraph] VALGRIND_TYPE is set to '${VALGRIND_TYPE}', skipping flamegraph generation."
+fi
 
 # Check if everything went well
 exit $FAIL
diff --git a/test/network_tests/memory_tests/conf/memory_test_slave_starter.sh.in b/test/network_tests/memory_tests/conf/memory_test_slave_starter.sh.in
--- a/test/network_tests/memory_tests/conf/memory_test_slave_starter.sh.in
+++ b/test/network_tests/memory_tests/conf/memory_test_slave_starter.sh.in
@@ -3,6 +3,47 @@
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
-export VSOMEIP_CONFIGURATION=memory_test_service.json
-export VSOMEIP_APPLICATION_NAME="service-sample"
-./memory_test_service
+
+FLAMEGRAPH_DIR=/opt/flamegraph/
+VALGRIND_TYPE=@VALGRIND_TYPE@
+
+export VSOMEIP_CONFIGURATION=memory_test_client.json
+export VSOMEIP_APPLICATION_NAME="client-sample"
+PERF_TOOL=$(find /usr/lib/linux-tools* -type f -name "perf" | head -n 1)
+
+if [ ! -f "$PERF_TOOL" ]; then
+    echo "Failed to find installation of perf."; exit 1;
+fi
+
+# If VALGRIND_TYPE is empty, run under perf; otherwise run normally
+if [ -z "${VALGRIND_TYPE}" ]; then
+    echo "[flamegraph] Starting memory_test_client under perf recording..."
+    $PERF_TOOL record -F 99 -g -o memory_test_client.perf.data -- ./memory_test_client
+else
+    ./memory_test_client
+fi
+
+# Generate flamegraph from recorded perf data (only if VALGRIND_TYPE is empty)
+if [ -z "${VALGRIND_TYPE}" ] && [ -f memory_test_client.perf.data ]; then
+    echo "[flamegraph] Perf data found, generating flamegraph..."
+    # Generate interactive SVG flamegraph (open directly in any browser)
+    $PERF_TOOL script -i memory_test_client.perf.data \
+        | $FLAMEGRAPH_DIR/stackcollapse-perf.pl \
+        | $FLAMEGRAPH_DIR/flamegraph.pl > memory_test_client_flamegraph.svg
+    if [ $? -eq 0 ]; then
+        echo "[flamegraph] SVG flamegraph generated: memory_test_client_flamegraph.svg"
+    else
+        echo "[flamegraph] ERROR: SVG flamegraph generation failed!" >&2
+    fi
+
+    # Generate perf script text file for import into Firefox Profiler
+    # (profiler.firefox.com -> "Load a profile from file")
+    $PERF_TOOL script -i memory_test_client.perf.data > memory_test_client_firefox_profiler.perf
+    if [ $? -eq 0 ]; then
+        echo "[flamegraph] Firefox Profiler file generated: memory_test_client_firefox_profiler.perf"
+    else
+        echo "[flamegraph] ERROR: Firefox Profiler file generation failed!" >&2
+    fi
+elif [ -n "${VALGRIND_TYPE}" ]; then
+    echo "[flamegraph] VALGRIND_TYPE is set to '${VALGRIND_TYPE}', skipping flamegraph generation."
+fi
